### ISSUE TITLE
Documentation Update: "Running a Superpowers server from the command line"

### ISSUE THREAD

**Issue by Occult-Dev** [superpowers/docs.superpowers-html5.com#12]
The instructions under "**Running a Superpowers server from the command line**" on this page: http://docs.superpowers-html5.com/en/getting-started/setting-up-superpowers
don't appear to work anymore.

The error thrown in the console is saying it can't find the `server` folder within `resouces/app`.

I'm guessing this is due to the app and server being split?

**Comment by elisee** [comment]
Ah. Indeed, you should download `superpowers-core` directly from https://github.com/superpowers/superpowers-core/releases. I'll update the page! Thanks for the report.

**Comment by Occult-Dev** [comment]
No problem! Someone was having issues with it in the irc so I figured I should post it here.
Thanks for the quick response!

**Comment by elisee** [comment]
Fixed in ac953f5fd8e820a353c3133364ebf0915f43795b and 7e6b5997624c9b38ebb1eefb2d4ea638f7b37eb7.
